config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: { registrations: 'users/registrations',
                            omniauth_callbacks: 'users/omniauth_callbacks' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'
  resources :posts do
    member do
      defaults likeable_type: 'Post' do
        post 'like', to: 'likes#create'
        delete 'unlike', to: 'likes#destroy'
      end

      resources :comments, shallow: true do
        member do
          defaults likeable_type: 'Comment' do
            post 'like', to: 'likes#create'
            delete 'unlike', to: 'likes#destroy'
          end
        end
      end
    end
  end

  resources :users, only: %i[index show update], shallow: true do
    member do
      post 'follow', to: 'follows#create'
      delete 'unfollow', to: 'follows#destroy'
      resources :profiles, only: %i[show edit update]
    end
  end

  resources :rooms, only: %i[index show new create] do
    member do
      resources :messages, only: %i[new create]
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user

  has_many :likes, as: :likeable

  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: %i[index new create]

  def index
    @comments = Comment.where(commentable_type: 'Post', commentable: @post).order(created_at: :desc)
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @comment = Comment.new(commentable: @post, user: current_user)
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.commentable = @post
    @comment.user = current_user
    if @comment.save
      flash.now[:notice] = 'Comment was successfully created.'
      respond_to(&:turbo_stream)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      flash[:notice] = 'Comment was successfully updated.'
      redirect_to @comment
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    return unless @comment.destroy

    flash[:notice] = 'Comment was successfully deleted.'
    redirect_to @comment.commentable
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/views/comments/_comment.html.erb
<div class='comment <%= "own" if comment.user == current_user %>'>
  <%= turbo_frame_tag "comment_#{comment.id}" do %>
    <div class="main">
      <p><%= comment.body %></p>
      <div class="profile">
        <%= image_tag comment.user.avatar.variant(:thumb) || 'sample.svg' , class: "profile_image", title: comment.user.full_name %>
      </div>
    </div>

    <div class="footer">
      <div class="actions">
        <div class="like">
          <%= button_to image_tag('heart.svg', alt: "Like"),
              like_comment_path(comment),
              method: :post unless current_user.liked?(comment) %>

          <%= button_to image_tag('heart_filled.svg', alt: "Unlike"),
              unlike_comment_path(comment),
              method: :delete if current_user.liked?(comment) %>
          <div class="like_count">
            <%= comment.likes.count %>
          </div>
        </div>

        <div class="misc">
          <% if current_user == comment.user %>
            <%= link_to edit_comment_path(comment) do %>
              <%= image_tag 'edit.svg', alt: "Edit" %>
            <% end %>

            <%= link_to comment, data: { turbo_method: "delete", turbo_confirm: "Are you sure?", turbo_frame: "_top"} do %>
              <%= image_tag 'delete.svg', alt: "Delete" %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_with model: @comment, data: { controller: "form", action: "turbo:submit-end->form#reset" } do |f| %>
  <%= render partial: "shared/errors", locals: { object: @comment } %>
  <%= f.text_area :body, placeholder: "Write a comment..." %>
  <%= f.submit "COMMENT", class: "comment_submit" %>
<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.prepend('comment_list', partial: 'comments/comment', locals: { comment: @comment }) %>
<%= turbo_stream.update('flash', partial: 'layouts/flash') %>

app/views/comments/edit.html.erb
<%= turbo_frame_tag "comment_#{@comment.id}" do %>
  <%= render partial: "form", comment: @comment %>
  <%= link_to "Back", @comment %>
<% end %>

app/views/comments/index.html.erb
<%= turbo_frame_tag "comments" do %>
  <%= turbo_frame_tag "new_comment", src: new_comment_path(@post) %>

  <h3>Comments</h3>
  <div class="comments" id="comment_list">
    <%= render @comments %>
  </div>
<% end %>

app/views/comments/new.html.erb
<%= turbo_frame_tag "new_comment" do %>
  <%= render 'comments/form', comment: @comment %>
<% end %>

app/views/comments/show.html.erb
<%= render @comment %>