config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: { registrations: 'users/registrations',
                            omniauth_callbacks: 'users/omniauth_callbacks' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'
  resources :posts do
    member do
      defaults likeable_type: 'Post' do
        post 'like', to: 'likes#create'
        delete 'unlike', to: 'likes#destroy'
      end

      resources :comments, shallow: true do
        member do
          defaults likeable_type: 'Comment' do
            post 'like', to: 'likes#create'
            delete 'unlike', to: 'likes#destroy'
          end
        end
      end
    end
  end

  resources :users, only: %i[index show update], shallow: true do
    member do
      post 'follow', to: 'follows#create'
      delete 'unfollow', to: 'follows#destroy'
      resources :profiles, only: %i[show edit update]
    end
  end

  resources :rooms, only: %i[index show new create] do
    member do
      resources :messages, only: %i[new create]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable,
         :omniauthable, omniauth_providers: %i[github google_oauth2]

  has_many :posts
  has_many :comments
  has_many :likes
  has_one :profile
  has_many :hobies, through: :profile

  has_many :active_follows, class_name: 'Follow', foreign_key: :follower_id
  has_many :following, through: :active_follows, source: :followee
  has_many :passive_follows, class_name: 'Follow', foreign_key: :following_id
  has_many :followers, through: :passive_follows, source: :follower
  has_many :followed_posts, through: :following, source: :posts

  has_one_attached :avatar do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100], preprocessed: true
  end
  has_one_attached :cover_photo

  validates :first_name, :second_name, presence: true
  validates :avatar, content_type: %i[png jpg jpeg]
  validates :cover_photo, content_type: %i[png jpg jpeg]

  accepts_nested_attributes_for :profile

  def full_name
    "#{first_name} #{second_name}"
  end

  def follow(user)
    following << user
  end

  def unfollow(user)
    following.delete(user)
  end

  def following?(user)
    following.include?(user)
  end

  def like(likeable)
    likes.create(likeable:, user: self)
  end

  def unlike(likeable)
    likes.find_by(likeable_id: likeable.id).destroy
  end

  def liked?(likeable)
    likes.find_by likeable:
  end

  def posts_feed
    Post.where(user: following).or(Post.where(user: self)).order(created_at: :desc)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.first_name = auth.info.first_name || auth.info.name
      user.second_name = auth.info.last_name || auth.info.nickname
      user.avatar.attach(io: URI.parse(auth.info.image).open, filename: 'avatar.jpeg')
      user.build_profile(bday: Date.today)
      user.skip_confirmation!
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Github') if is_navigational_format?
    else
      set_flash_message(:notice, :failure, kind: 'Github', reason: @user.errors.full_messages.join(' '))
      redirect_to new_user_session_url
    end
  end

  def google_oauth2
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Google') if is_navigational_format?
    else
      set_flash_message(:notice, :failure, kind: 'Google', reason: @user.errors.full_messages.join(', '))
      redirect_to new_user_session_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    build_resource
    resource.build_profile
    respond_with resource
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: [:first_name, :second_name,
                                             { profile_attributes: %i[description gender bday address] }])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show update]

  def index
    @following = current_user.following
    @followers = current_user.followers
    @not_following = User.where.not(id: @following.ids << current_user.id)
  end

  def show; end

  def update
    if @user.update(user_params)
      flash[:notice] = 'Profile was successfully updated.'
      redirect_to @user
    else
      render :show, status: :unprocessable_entity
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :second_name, :avatar, :cover_photo)
  end
end

app/views/users/_user.html.erb
<div class="user_card" id="user_<%= user.id %>">
  <%= link_to user_path(user) do %>
    <div class="avatar">
      <%= image_tag (user.avatar if user.avatar.attached? && user.avatar.persisted?) ||'sample.svg', class: "avatar" %>
    </div>
    <div class="name">
      <%= user.full_name %>
    </div>
  <% end %>

  <div class="actions">
    <%= button_to image_tag('follow.svg', alt: 'Follow'), follow_user_path(user), method: :post if !current_user.following?(user) %>
    <%= button_to image_tag('unfollow.svg', alt: 'Unfollow'), unfollow_user_path(user), method: :delete if current_user.following?(user) %>
  </div>
</div>

app/views/users/index.html.erb
<h2>Followers</h2>
<div id="followers" class="users_container">
  <%= render partial: "user", collection: @followers, as: :user %>
</div>

<h2>Following</h2>
<div id="following" class="users_container">
  <%= render partial: "user", collection: @following, as: :user %>
</div>

<h2>You may know these hikers</h2>
<div id="not_followed" class="users_container">
  <%= render partial: "user", collection: @not_following, as: :user %>
</div>

app/views/users/show.html.erb
<%= content_tag :div, class: 'profile' do %>

<%= content_tag :div, class: 'banner', style: "background-image: url(#{@user.cover_photo.persisted? ? rails_blob_url(@user.cover_photo) : image_path('default_cover.jpg')})" do %>
  <% if @user == current_user %>
    <%= form_with model: @user do |f| %>
      <%= f.label :avatar do %>
        <%= image_tag 'upload.svg', alt: 'Update Avatar' %>
      <% end %>
      <%= f.file_field :avatar, class: 'hidden', onchange: 'this.form.submit()' %>

      <%= f.label :cover_photo do %>
        <%= image_tag 'upload.svg', alt: 'Update Cover Photo' %>
      <% end %>
      <%= f.file_field :cover_photo, class: 'hidden', onchange: 'this.form.submit()' %>

      <%= render partial: "shared/errors", locals: { object: @user } %>
    <% end %>
  <% end %>

  <%= image_tag (@user.avatar if @user.avatar.attached? && @user.avatar.persisted?) || "sample.svg", class: 'avatar' %>
<% end %>

<%= content_tag :div, class: 'details' do %>
  <%= content_tag :div, class: 'first_part' do %>
    <%= content_tag :h1, @user.full_name %>
    <%= content_tag :div, @user.email %>
  <% end %>

  <%= content_tag :div, class: 'actions' do %>
    <%= button_to image_tag('follow.svg', alt: 'Follow'), follow_user_path(@user), method: :post if !current_user.following?(@user) %>
    <%= button_to image_tag('unfollow.svg', alt: 'Unfollow'), unfollow_user_path(@user), method: :delete if current_user.following?(@user) %>
  <% end unless @user == current_user %>

  <%= turbo_frame_tag "profile", src: profile_path(@user.profile) if @user.profile %>
<% end %>

<%= content_tag :div, class: 'flex_column flex_center' do %>
  <%= turbo_frame_tag "new_post", src: new_post_path if @user == current_user %>
  <%= turbo_frame_tag "posts", src: posts_path(user: @user) %>
<% end %>

<% end %>