config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: { registrations: 'users/registrations',
                            omniauth_callbacks: 'users/omniauth_callbacks' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'
  resources :posts do
    member do
      defaults likeable_type: 'Post' do
        post 'like', to: 'likes#create'
        delete 'unlike', to: 'likes#destroy'
      end

      resources :comments, shallow: true do
        member do
          defaults likeable_type: 'Comment' do
            post 'like', to: 'likes#create'
            delete 'unlike', to: 'likes#destroy'
          end
        end
      end
    end
  end

  resources :users, only: %i[index show update], shallow: true do
    member do
      post 'follow', to: 'follows#create'
      delete 'unfollow', to: 'follows#destroy'
      resources :profiles, only: %i[show edit update]
    end
  end

  resources :rooms, only: %i[index show new create] do
    member do
      resources :messages, only: %i[new create]
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  after_create_commit { broadcast_prepend_to 'rooms' }

  has_many :messages

  validates :name, presence: true
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])
    @messages = @room.messages
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    render :new, status: :unprocessable_entity unless @room.save
  end

  private

  def room_params
    params.require(:room).permit(:name)
  end
end

app/views/rooms/_form.html.erb
<%= form_with model: room, data: { controller: "form", action: "turbo:submit-end->form#reset" } do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= render partial: "shared/errors", locals: { object: room } %>

  <%= f.submit 'CREATE ROOM', class: 'btn' %>
<% end %>

app/views/rooms/_room.html.erb
<div class="room">
  <%= link_to room.name, room, data: { turbo_frame: 'messages' }%>
</div>

app/views/rooms/index.html.erb
<div class="chat_box">
  <div class="side_nav">
    <%= turbo_stream_from 'rooms' %>
    <div id="rooms">
      <%= render @rooms %>
    </div>
    <%= turbo_frame_tag "new_room", src: new_room_path %>
  </div>

  <div class="body">
    <%= turbo_frame_tag "messages" do %>
    <% end %>
  </div>
</div>

app/views/rooms/new.html.erb
<%= turbo_frame_tag "new_room" do %>
  <%= render partial: 'form', locals: { room: @room } %>
<% end %>

app/views/rooms/show.html.erb
<%= turbo_frame_tag "messages" do %>
  <div class="room_name"><%= @room.name %></div>

  <%= turbo_stream_from @room %>
  <div class="reversed">
    <div id="message_list">
      <%= render @messages  %>
    </div>
  </div>

  <div class='new_message_form'>
    <%= turbo_frame_tag "new_message", src: new_message_path %>
  </div>
<% end %>