config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: { registrations: 'users/registrations',
                            omniauth_callbacks: 'users/omniauth_callbacks' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'
  resources :posts do
    member do
      defaults likeable_type: 'Post' do
        post 'like', to: 'likes#create'
        delete 'unlike', to: 'likes#destroy'
      end

      resources :comments, shallow: true do
        member do
          defaults likeable_type: 'Comment' do
            post 'like', to: 'likes#create'
            delete 'unlike', to: 'likes#destroy'
          end
        end
      end
    end
  end

  resources :users, only: %i[index show update], shallow: true do
    member do
      post 'follow', to: 'follows#create'
      delete 'unfollow', to: 'follows#destroy'
      resources :profiles, only: %i[show edit update]
    end
  end

  resources :rooms, only: %i[index show new create] do
    member do
      resources :messages, only: %i[new create]
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :comments, as: :commentable
  has_many :likes, as: :likeable
  has_many_attached :images

  validates :title, :body, presence: true
  validates :images, content_type: %i[png jpg jpeg]
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.where(user: params[:user] || current_user).order(created_at: :desc).page(params[:page])
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      flash.now[:notice] = 'Post was successfully created.'
      respond_to(&:turbo_stream)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = 'Post was successfully updated.'
      redirect_to @post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    flash[:notice] = 'Post was successfully deleted.' if Post.find(params[:id]).destroy

    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, images: [])
  end
end

app/views/posts/_form.html.erb
<%= form_with model: post, data: { controller: "form", action: "turbo:submit-end->form#reset" } do |f| %>
  <%= f.text_field :title, placeholder: "Title" %>
  <%= f.text_area :body, placeholder: "What's on your mind?" %>
  <% post.images.each do |image| %>
    <%= f.hidden_field :images, multiple: true, value: image.signed_id if image.persisted? && post.images.attached? %>
  <% end %>
  <%= f.file_field :images, multiple: true, data: { controller: 'form', action: 'change->form#checkSize' } %>

  <%= render partial: "shared/errors", locals: { object: post } %>

  <%= f.submit 'SAVE POST', class: 'btn' %>
<% end %>

app/views/posts/_post.html.erb
<div class="post_card">
  <%= turbo_frame_tag "post_#{post.id}" do %>
    <%= link_to post, class: "card_link", data: { turbo_frame: "_top" } do %>
      <h3><%= post.title %></h3>
      <p class="body"><%= post.body %></p>

      <div class="images">
        <% post.images.each do |image| %>
          <%= image_tag image %>
        <% end %>
      </div>

      <div class="user_name">
        <%= post.user.full_name %>
      </div>
    <% end %>

    <div class="actions">
      <div class="like">
        <%= button_to image_tag('heart.svg', alt: "Like"), like_post_path(post), method: :post unless current_user.liked?(post) %>
        <%= button_to image_tag('heart_filled.svg', alt: "Unlike"), unlike_post_path(post), method: :delete if current_user.liked?(post) %>
        <div class="like_count">
          <%= post.likes.count %>
        </div>
      </div>

      <div class="misc">
        <%= link_to post, data: { turbo_frame: "_top" } do %>
          <%= image_tag 'comment.svg' %>
        <% end %>
        <% if current_user == post.user %>
          <%= link_to edit_post_path(post) do%>
            <%= image_tag 'edit.svg', alt: "Edit"%>
          <% end %>
          <%= link_to post, data: { turbo_method: "delete", turbo_confirm: "Are you sure?", turbo_frame: "_top"} do %>
            <%= image_tag 'delete.svg', alt: "Delete" %>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/create.turbo_stream.erb
<%= turbo_stream.prepend('post_list', partial: 'posts/post', locals: { post: @post }) %>
<%= turbo_stream.update('flash', partial: 'layouts/flash') %>

app/views/posts/edit.html.erb
<%= turbo_frame_tag "post_#{@post.id}" do %>
  <%= render partial: "form", locals: { post: @post } %>
  <%= link_to "Back", @post %>
<% end %>

app/views/posts/index.html.erb
  <div class="flex_column flex_center">
    <%= turbo_frame_tag "new_post", src: new_post_path %>

    <%= turbo_frame_tag "posts" do %>
      <div class="container" id="post_list">
        <%= render @posts %>
        <%= paginate @posts %>
      </div>
    <% end %>
  </div>

app/views/posts/new.html.erb
<%= turbo_frame_tag "new_post" do %>
  <div class="post_card">
    <%= render partial: "form", locals: { post: @post } %>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="post_discussion">
  <%= render @post %>

  <%= turbo_frame_tag "comments", src: comments_path(@post) %>
</div>